# Mailhandler Comment settings schema.
inmail.plugin.handler.mailhandler_comment:
  label: 'Comment handler configuration'
  type: mapping
  mapping:
    entity_type:
      label: 'Referenced entity type'
      type: string
